Feature
Hassaanjbaig-code/Capstone-Project pull request #1
Opened 2022-11-24 05:18 UTC by Hassaanjbaig-code

For this project, I have:
-Created a two-page website with a home and about page.
-Created a side navigation menu for smaller screens.
-Created a dynamically generated featured games section from a featuredGames object.
-Added a more button on the featured games section that expands to display more games from the featured games object and also has a less button which is you to less expand.
-At **Day-1** start the project by working on the home page by finding of data
- At **Day-2** starting the project About section working on both mobile and desktop versions also complete the home page
- At **Day -3**  giving functionality to the main and about page also creating the Dynamic section and also fixing responsive stuff

Show the project live by click on [This link](url)

2022-11-24 11:13 UTC, emmiiorji requested changes
Hi @Hassaanjbaig-code, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A-little-more](https://user-images.githubusercontent.com/20554583/203690360-733c8074-87d0-496d-8c11-1cb0c79acc7b.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow
- Good documentation with the new readme template


## Required Changes ♻️

- As mentioned in the requirements, kindly include your recorded  video of maximum length 5 minutes, where you present the features of the project. The video is expected to contain a demo of the project, showing the pages in different screen sizes and a highlight about a piece of the code you find interesting or are proud of making.
- In the case of future projects, kindly ensure that all changes made in a milestone are contained in the same pull request for easier reviews. In this case, all the code from scratch is under review. You have committed the readme file to the master branch.

- _Check the comments under the review for more required changes._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 11:13 UTC, emmiiorji commented on readme.md
>  > Add a link to your deployed project.
[Optional] Kindly consider removing the section descriptions in the readme as illustrated below for an example. As you may notice, they're only notes to the project's author on how to use the template.

![image](https://user-images.githubusercontent.com/20554583/203750805-c44f9027-a987-4e8d-8f54-214a8aaa5a2a.png)

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +    <!-- <h1>Hello world</h1> -->
Kindly remove unused pieces of code in order to make the code base more concise.

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +              "
As one of the best practices, kindly avoid the use of inline styling. This will help for easier code reuse.

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +            "
As mentioned above and as a best practice, kindly avoid the use of inline styles.

You have specified the same set of styles in several places. This suggests that the elements involved could be assigned a class and then have the class styled to affect each of them.

2022-11-24 11:13 UTC, emmiiorji commented on index2.html
> +<!DOCTYPE html>
[Optional] As a best practice, I think it'll be good not to have 2 index files in the same directory. Since this is the about page, kindly give the file a name that suggests so. e.g _about.html_

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +              color: #444140;
Your hero section looks great. However, it needs a little adjustment to make it match the design template.

- Kindly add the margin between the content and the container. Also notice that the content of the main program section aligns with it.
- The height of the section is more on Cindy's design. Kindly increase it to typically the height of the screen at minimum.

Your design:
![image](https://user-images.githubusercontent.com/20554583/203760144-e8703444-d005-495b-b6f4-e27460aa359b.png)
![image](https://user-images.githubusercontent.com/20554583/203761265-d903c7c3-a756-4747-a80e-71f862604277.png)


Cindy's design:
![image](https://user-images.githubusercontent.com/20554583/203760190-d4e9062a-8c13-4339-bbd5-f997b34f84ed.png)
![image](https://user-images.githubusercontent.com/20554583/203761066-d8b8e369-b54d-4b4e-a7c4-2fde05342b6a.png)

2022-11-24 11:13 UTC, emmiiorji commented on readme.md
Kindly include an appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). You may do this in the "Acknowledgements" section of the readme file.

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +            fans celebration of the xbox games showcase
Please, adjust the main program section to be similar to the given design. Kindly adjust the following:

- Kindly include the hover effect as shown by the white-bordered card
- The content of the section aligns with the content of the hero section on the left and right
- The orange underline of the title "Main Program" is centre-aligned
- The margin above and below the card titles should be less
- The descriptions in each of the cards are centre-aligned

Your design:
![image](https://user-images.githubusercontent.com/20554583/203763901-84884f7b-5971-4e15-9473-af203eacf7af.png)


Cindy's design:
![image](https://user-images.githubusercontent.com/20554583/203763980-fc25c59a-d6b0-4069-a8f5-c14c626c69c9.png)

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +    <section class="Featured" id="Featured"></section>
Kindly adjust the speakers section in order to match the design.

See the illustrations in the image for the adjustment to be made:

Your design:
![image](https://user-images.githubusercontent.com/20554583/203769672-044ff994-360a-4cbb-9224-3fa1409b49d8.png)


Cindy's design:
![image](https://user-images.githubusercontent.com/20554583/203769808-d11e94fe-47e1-42ec-b3ed-f5768f60a7c2.png)

2022-11-24 11:13 UTC, emmiiorji commented on index.html
> +                color: #444140;
On the mobile version, kindly centralize the content of the page.

Your design:
![image](https://user-images.githubusercontent.com/20554583/203770315-a9327dd6-9f9b-4f5f-a988-764cba793b80.png)

Cindy's design:
![image](https://user-images.githubusercontent.com/20554583/203770459-133303d0-79cd-44d6-ab36-70e71103a79d.png)

2022-11-24 18:32 UTC, PinkMoon25 requested changes
Hi @Hassaanjbaig-code , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/zyjCXPXNo39i0CB467/giphy.gif"/>

 ## Highlights
Linter checks are passing :heavy_check_mark: 
Good commit messages :heavy_check_mark: 
Adhered to GitHub flow :heavy_check_mark: 
Good documentation with the new readme template :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 18:32 UTC, PinkMoon25 commented on index.html
> +      </header>
- [ ] As requested by the previous reviewer https://github.com/Hassaanjbaig-code/Capstone-Project/pull/1#discussion_r1031343860 Please make sure your header and Hero section is similar to the original design as much as possible currently your design is :point_down: 
![image](https://user-images.githubusercontent.com/97521557/203845207-4e089a42-3b09-45d4-9771-25b1f2f4268e.png)

I think you can use 100vh height on your main and remove the fixed height and width from your home-1 and add width 100% and align-items: center and use justify-content: space around or center for your header, this should fix the style for the design
```
main {
  background-position: 24px 57px;
  background-size: cover;
  height: 100vh;
}

.Home-1 {
  width: 100%;
  align-items: center;
}

header {
  width: 100%;
  background-color: #fff;
  justify-content: center;
}
```

2022-11-24 18:32 UTC, PinkMoon25 commented on index.html
> +            exclusive trailer.
- [ ] As requested by the previous reviewer https://github.com/Hassaanjbaig-code/Capstone-Project/pull/1#discussion_r1031361658 Please add the hover effct to your cards you can do some thing like 
```
card-1.left.card-im:hover {
  border: 1px solid white;
}
```

2022-11-24 18:32 UTC, PinkMoon25 commented on index.html
> +    <section class="Featured" id="Featured"></section>
- [ ] Good job making the changes to your featured section, But as requested it is still not matching the design guidelines, please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/203846970-1337342f-2a68-4098-94cb-08115853d661.png)

I think we can improve this by setting 
```
.maincardsec {
  display: flex;
  width: 100%;
  justify-content: center;
  flex-direction: row;
  gap: 24px;
}
```

2022-11-24 18:32 UTC, PinkMoon25 commented on about.html
> +        </div>
As requested by the previous reviewer please fix the mobile section as it currently has overflow, Try to decrease the font-size for your main title and remove fixed width and use flex or grid for a more responsive layout currently your layout is not responsive on  mobile screen please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/203848193-3f229cf5-31d4-48cd-ae4d-5f97738d99a6.png)

2022-11-25 16:42 UTC, uwadonat approved these changes
## Hi @Hassaanjbaig-code,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-12 19:29 UTC, merged